#name: "${{ parameters.env }}.${{ parameters.cluster }}.${{ parameters.location }}"

trigger: none

pool:
  vmImage: 'ubuntu-latest'

parameters:
  - name: migrationConfig
    displayName: Migration Config
    type: object

variables:
  - name: service_connection
    value: GA

steps:
  - task: Bash@3
    displayName: "Print Migration config"
    inputs:
      targetType: 'inline'
      script: |
        echo ${{ parameters.migrationConfig.project }}
        echo "${{ convertToJson(parameters.migrationConfig.dbs_to_migrate) }}"

  - task: AzureKeyVault@1
    displayName: Retrieve admin password for single server
    inputs:
      ConnectedServiceName: ${{ variables.service_connection }}
      keyVaultName: ${{ parameters.migrationConfig.single_server_kv_name }}
      secretsFilter: ${{ parameters.migrationConfig.single_server_secret_name }}
      runAsPreJob: false


  - task: AzureKeyVault@1
    displayName: Retrieve admin password for flexible server
    inputs:
      ConnectedServiceName: ${{ variables.service_connection }}
      keyVaultName: ${{ parameters.migrationConfig.flexible_server_kv_name }}
      secretsFilter: ${{ parameters.migrationConfig.flexible_server_secret_name }}
      runAsPreJob: false

#######
## Pipeline tasks

# 1. Take params
# 2. Validation (may not need to do any of this)
#    - check that the source and target db's exist and that they are the right type.
#    - check that the migration name doesn't exist (may just be able to leave this out)
#    - check that the flex dbs have the same server settings (cli will also do this)

# 3. Get Admin creds for both dbs and store as vars
# 4. Create json file for the migration
# 5. Run the migration
# 6. Monitor the migration until it finishes
# 7. make sure pipeline fails if the migration fails

# Things to think about
# Timeout of the pipeline, increase it to as much as possible 24 hours maybe
