#name: "${{ parameters.env }}.${{ parameters.cluster }}.${{ parameters.location }}"

trigger: none

pool:
  vmImage: 'ubuntu-latest'

parameters:
  - name: migrationConfig
    displayName: Migration Config
    type: object

variables:
  - name: service_connection
    value: GA

steps:
  - task: AzureCLI@2
    displayName: "Create migration"
    inputs:
      azureSubscription: ${{ variables.service_connection }}
      scriptType: bash
      scriptPath: migration/migration.sh
    env:
      project: ${{ parameters.migrationConfig.project }}
      environment: ${{ parameters.migrationConfig.environment }}
      migration_name: ${{ parameters.migrationConfig.migration_name }}
      subscription: ${{ parameters.migrationConfig.subscription }}
      resource_group: ${{ parameters.migrationConfig.resource_group }}
      flexible_server_name: ${{ parameters.migrationConfig.resource_group }}
      dbs_to_migrate: ${{ convertToJson(parameters.migrationConfig.dbs_to_migrate) }}
      single_server_resource_id: ${{ parameters.migrationConfig.single_server_resource_id }}
      overwrite_target_dbs: ${{ parameters.migrationConfig.overwrite_target_dbs }}
      flexible_server_kv_name: ${{ parameters.migrationConfig.flexible_server_kv_name }}
      flexible_server_secret_name: ${{ parameters.migrationConfig.flexible_server_secret_name }}
      single_server_kv_name: ${{ parameters.migrationConfig.single_server_kv_name }}
      single_server_secret_name: ${{ parameters.migrationConfig.single_server_secret_name }}

#######
## Pipeline tasks

## Prerequisites
# - flexible server deployed
# - "Get" permissions to kv secrets for dad693c4-36ad-468f-94e9-76faa4bc844b

# Tasks
# 6. Monitor the migration until it finishes
# 7. make sure pipeline fails if the migration fails

# Things to think about
# Timeout of the pipeline, increase it to as much as possible 24 hours maybe
