name: "Migration - ${{ parameters.migrationConfig.flexible_server_name }}"

trigger: none

pool:
  vmImage: 'ubuntu-latest'

parameters:
  - name: migrationConfig
    displayName: Migration Config
    type: object

variables:
  - name: service_connection
    value: GA

steps:
  - task: AzureCLI@2
    displayName: "Create migration"
    inputs:
      azureSubscription: ${{ variables.service_connection }}
      scriptType: bash
      scriptPath: migration/migration.sh
    env:
      migration_name: ${{ parameters.migrationConfig.migration_name }}
      subscription: ${{ parameters.migrationConfig.subscription }}
      resource_group: ${{ parameters.migrationConfig.resource_group }}
      flexible_server_name: ${{ parameters.migrationConfig.flexible_server_name }}
      dbs_to_migrate: ${{ convertToJson(parameters.migrationConfig.dbs_to_migrate) }}
      single_server_resource_id: ${{ parameters.migrationConfig.single_server_resource_id }}
      overwrite_target_dbs: ${{ parameters.migrationConfig.overwrite_target_dbs }}
      kv_subscription: ${{ parameters.migrationConfig.kv_subscription }}
      flexible_server_kv_name: ${{ parameters.migrationConfig.flexible_server_kv_name }}
      flexible_server_secret_name: ${{ parameters.migrationConfig.flexible_server_secret_name }}
      single_server_kv_name: ${{ parameters.migrationConfig.single_server_kv_name }}
      single_server_secret_name: ${{ parameters.migrationConfig.single_server_secret_name }}
