# Name of migration this needs to be unique to the flexible server (target server), the same name can't be used twice.
migration_name: migration_1

# Subscription of the flexible server
subscription:

# Resource group of the flexible server
resource_group:

# Name of the flexible server
flexible_server_name:

# Databases to migrate - max 8 at a time
dbs_to_migrate:
  - postgres

# Resource ID of the single server (source server)
single_server_resource_id: /subscriptions/xxxxxx/resourceGroups/xxxxxx/providers/Microsoft.DBforPostgreSQL/servers/xxxxxx

# Whether to overwrite existing target dbs
overwrite_target_dbs: true

# Subscription name of the key vault that holds the secret with the postgres admins' password
kv_subscription:

# Key vault name and secret name with flexible servers' admin password
flexible_server_kv_name:
flexible_server_secret_name:

# Key vault name and secret name with single servers' admin password
single_server_kv_name:
single_server_secret_name:
